rm: Show object has been delete msg when delete marker is found
minio/mc pull request #3407
Opened 2020-09-16 13:01 UTC by vadmeste

HEAD objet returns 404 with a delete-marker header when the object is a
delete-marker in a versioning bucket. This PR will show a better error
message in that case.

2020-09-20 05:04 UTC, harshavardhana requested changes
We should also show perhaps help where we say that `Object is marked as deleted, please use '--vid' to delete a specific version`

2020-09-20 05:04 UTC, harshavardhana commented on cmd/client-errors.go
> +	return "Object has been deleted"
```suggestion
	return "Object is marked as deleted"
```

2020-09-21 14:57 UTC, vadmeste commented
> please use '--vid' to delete a specific version

I think you mean please use `mc undo xxxx` to undelete this object ?

2020-09-21 17:58 UTC, harshavardhana commented
> I think you mean please use `mc undo xxxx` to undelete this object ?

yeah @vadmeste

2020-09-21 17:59 UTC, harshavardhana approved these changes

2020-09-21 18:19 UTC, kannappanr approved these changes
LGTM

2020-09-21 18:42 UTC, merged