doc: Update missing versioning documentation
minio/mc pull request #3417
Opened 2020-09-23 15:37 UTC by vadmeste

Remove stale 'lock' command as well.

2020-09-30 20:14 UTC, kannappanr approved these changes

2020-09-30 21:17 UTC, eco-minio requested changes
Few minor changes

2020-09-30 21:17 UTC, eco-minio commented on docs/minio-client-complete-guide.md
> +*Example: Display the first lines of the content of an object, 1 year earlier*
```suggestion
*Example: Display the first line of the content of an object, 1 year earlier*
```

2020-09-30 21:17 UTC, eco-minio commented on docs/minio-client-complete-guide.md
> +c legalhold info myminio/mybucket/prefix --recursive
```suggestion
mc legalhold info myminio/mybucket/prefix --recursive
```

2020-09-30 21:17 UTC, eco-minio commented on docs/minio-client-complete-guide.md
> +*Example: Roll back to object version of 10 days earlier while copying.*
```suggestion
*Example: Roll back to object version to 10 days earlier while copying.*
```

2020-10-01 09:06 UTC, vadmeste commented on docs/minio-client-complete-guide.md
> +| [**update** - manage software updates](#update)                                         | [**watch** - watch for events](#watch)                              | [**stat** - stat contents of objects
> #du does not redirect to appropriate anchor in the page (works for tag and admin below)

yes, du documentation was just missing, fixed it now

2020-12-21 21:58 UTC, kannappanr commented
@vadmeste Can you please resolve the conflicts. Will try to push this in quickly

2020-12-22 14:52 UTC, vadmeste commented
> @vadmeste Can you please resolve the conflicts. Will try to push this in quickly

@kannappanr done!

2020-12-22 17:15 UTC, eco-minio approved these changes
LGTM

2020-12-22 17:23 UTC, merged