Add a --label flag to mc admin bucket remote add command
minio/mc pull request #3443
Opened 2020-10-07 23:35 UTC by poornas

This label will be used in lieu of transition storage class for [ilm transition](https://github.com/minio/minio/pull/10565)

2020-10-23 01:28 UTC, kannappanr approved these changes
LGTM

2020-10-23 01:35 UTC, harshavardhana requested changes
I am not sure why is this service called `replication` shouldn't the examples be called `service=transition` ?

2020-10-23 01:35 UTC, harshavardhana commented on cmd/admin-bucket-remote-add.go
> +                 --service "replication" --region "us-west-1" --label "replica1"
```suggestion
                 --service "replication" --region "us-west-1" --label "hdd-tier"
```

2020-10-23 04:41 UTC, poornas commented
> I am not sure why is this service called `replication` shouldn't the examples be called `service=transition` ?

The ilm transition PR needs to be in before I can do that - currently only valid service is replication on minio master branch

2020-10-23 04:45 UTC, harshavardhana commented
> The ilm transition PR needs to be in before I can do that - currently only valid service is replication on minio master branch

Is label feature also available for replication ? if so how is it used?

2020-10-23 05:02 UTC, poornas commented
> > The ilm transition PR needs to be in before I can do that - currently only valid service is replication on minio master branch
> 
> Is label feature also available for replication ? if so how is it used?

no, this is just a tag to identify the remote and is ignored by replication. It is repurposed in ilm transition to also sub as the storage-class name.

2020-10-29 12:28 UTC, vadmeste approved these changes
LGTM

2020-10-29 17:58 UTC, merged