docs: update 'mc admin config' doc
minio/mc pull request #3522
Opened 2020-12-03 23:48 UTC by harshavardhana

2020-12-03 23:51 UTC, poornas approved these changes

2020-12-04 07:38 UTC, ebozduman requested changes

2020-12-04 07:38 UTC, ebozduman commented on docs/minio-admin-complete-guide.md
> +*Example: Get specific settings on 'etcd' sub-system.*
```suggestion
*Example: Get 'etcd' sub-system configuration.*
```

Maybe it is just me, but to me `specific settings on 'etcd' sub-system` sounds like user can get a specific setting or a configuration parameter of `etcd`, like:

```
$ mc admin config get myminio etcd path_prefix`
etcd path_prefix= 'prefix/'
```
but this is not valid command format, so it fails with an error message.

2020-12-04 07:41 UTC, harshavardhana commented on docs/minio-admin-complete-guide.md
> +  restore  rollback back changes to a specific config history
rollback is one term in computer terminology not `roll back` as in english

2020-12-04 07:46 UTC, ebozduman approved these changes
LGTM

2020-12-04 07:56 UTC, merged