wip: Add mc admin sc subcommands
minio/mc pull request #3566
Opened 2021-01-08 19:06 UTC by krisis

2021-01-15 01:46 UTC, poornas commented on cmd/admin-storage-class-add.go
> +		Usage: "cloud backend type. Valid options are '[s3, azure, gcs]'",
should also include minio  :)

2021-01-15 01:57 UTC, poornas requested changes

2021-01-15 01:57 UTC, poornas commented on cmd/admin-storage-class-add.go
> +  1. Configure a new storage class backed by AWS s3 using its Standard-IA storage class
```suggestion
  1. Configure a new storage class backend by AWS s3 using its Standard-IA storage class
```

2021-01-15 01:57 UTC, poornas commented on cmd/admin-storage-class-add.go
> +			fatalIf(probe.NewError(err), "Invalid configuration for s3 backed storage-class")
```suggestion
			fatalIf(probe.NewError(err), "Invalid configuration for s3 transition target")
```

2021-01-15 01:57 UTC, poornas commented on cmd/admin-storage-class-add.go
> +			fatalIf(probe.NewError(err), "Invalid configuration for azure backed storage-class")
```suggestion
			fatalIf(probe.NewError(err), "Invalid configuration for azure backend storage-class")
```

2021-01-15 01:57 UTC, poornas commented on cmd/admin-storage-class-add.go
> +			fatalIf(probe.NewError(err), "Invalid configuration for s3 backed storage-class")
`s3 backend storage-class` will be misleading and get confused with actual storage class used on s3

2021-01-15 01:57 UTC, poornas commented on cmd/admin-storage-class-add.go
> +	return madmin.StorageClassConfig{}
the command line should also take the target storage class where object should be tiered to. Seems to be missing for all 3 clouds

2021-03-12 20:13 UTC, poornas commented
can you fix conflicts here @krisis

2021-04-27 22:07 UTC, ravindk89 commented on cmd/admin-tier-add.go
> +		Usage: "AWS S3 or compatible object storage's storage-class. e.g AWS s3 suppports S3_STANDARD and S3_IA",
As discussed, should modify these to specify only supported storage classes:

- `STANDARD` , `REDUCED_REDUNDANCY` <- via [S3 spec](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html#AmazonS3-PutObject-request-header-StorageClass).

2021-04-27 22:08 UTC, ravindk89 commented on cmd/admin-tier-add.go
> +  2. Configure a new remote tier which transitions objects to AWS S3 Standard-IA storage class.
@krisis Need to change the `--storage-class` value here. Also probably referencing `REDUCED_REDUNDANCY` unless we're sure we can support `STANDARD_IA`

2021-05-05 21:13 UTC, ravindk89 approved these changes
So from a general perspective this looks good to me. The messaging I think is fine and the args look good.

2021-05-12 02:41 UTC, harshavardhana approved these changes

2021-05-12 02:42 UTC, merged