session: Fix resuming cp/mv session
minio/mc pull request #3580
Opened 2021-01-21 14:58 UTC by vadmeste

Session files contained a colored json which leaded a problem with
unparsing it, use encoding/json instead of the colorjson when
marshal/unmarshal session data.

To test:
`mc cp --continue /bin/cp/ play/bucket/`

2021-01-21 16:50 UTC, harshavardhana requested changes

2021-01-21 16:50 UTC, harshavardhana commented on cmd/cp-main.go
> +	stdjson "encoding/json"
we can use `jsoniter` here @vadmeste

2021-01-22 14:02 UTC, vadmeste commented on cmd/cp-main.go
> +	stdjson "encoding/json"
> we can use `jsoniter` here @vadmeste

good idea, done

2021-02-19 16:36 UTC, kannappanr approved these changes

2021-02-19 18:51 UTC, harshavardhana approved these changes

2021-02-19 18:51 UTC, merged