parallel-manager: Reduce parallelism when there is not enough memory
minio/mc pull request #3629
Opened 2021-03-01 12:17 UTC by vadmeste

Some users with low memory and good connection uploading some big files
can see memory crash, since mc will increase upload parallelism over
time when the bandwidth and the server is able to carry the load.

This PR will check the free OS memory before starting mirror/cp and will
estimate current memory usage based on uploaded objects sizes, it will
stop parallelism until the memory gets some room.

2021-03-14 21:44 UTC, harshavardhana approved these changes

2021-06-13 01:02 UTC, harshavardhana commented
Please fix the conflicts @vadmeste

2021-06-14 09:41 UTC, vadmeste commented
> Please fix the conflicts @vadmeste

Done

2021-08-20 15:23 UTC, harshavardhana requested changes

2021-08-20 15:23 UTC, harshavardhana commented on cmd/parallel-manager.go
> +	}
You can use `minio.OptimalPartInfo(objectSize, partSize)`

2021-08-23 22:20 UTC, harshavardhana approved these changes

2021-08-24 14:14 UTC, klauspost commented on cmd/parallel-manager.go
> +	runtime.ReadMemStats(&smem)
```suggestion
	runtime.GC()
	runtime.ReadMemStats(&smem)
```

2021-08-24 14:14 UTC, klauspost commented on cmd/parallel-manager.go
> +		maxMem = float64(memStats.Available) * 0.8 // use upto 80% of available memory.
This will account for the default `GOGC:100`.
```suggestion
		maxMem = float64(memStats.Available) / 2 // use upto 50% of available memory.
```

2021-09-01 09:16 UTC, harshavardhana approved these changes

2021-09-01 14:00 UTC, klauspost approved these changes
Sure, let's try it.

2021-09-01 16:07 UTC, merged

2021-11-17 07:01 UTC, mrsrvman commented
This PR does not solve the problem when running in docker with memory limits set

2021-11-17 07:03 UTC, mrsrvman commented
Look https://github.com/minio/mc/issues/3781