mc mirror -watch  event http://10.0.0.1:9000/test2/1.png sourceURLFull http://10.0.0.1:9000/test1fix eventPath not in source
minio/mc pull request #3647
Opened 2021-03-16 03:14 UTC by yyimen

mc mirror -watch minio/test1 /tmp/test1
eventPath http://10.0.0.1:9000/test2/1.png

add eventPath filter

2021-03-19 10:56 UTC, klauspost requested changes
Please describe what you are trying to achieve and how this issue is affecting you.

2021-03-19 10:56 UTC, klauspost commented on .vscode/launch.json
> +{
Remove please.

2021-03-19 10:56 UTC, klauspost commented on cmd/mirror-main.go
> +		//ymfix Skip the object,event http://10.0.0.1:9000/test2/1.png sourceURLFull http://10.0.0.1:9000/test1
?

2021-03-19 10:56 UTC, klauspost commented on cmd/watch-main.go
> +	//ymfix
? Remove

2021-03-19 10:56 UTC, klauspost commented on cmd/watch-main.go
> +					//ymfix
Remove

2021-04-15 23:59 UTC, harshavardhana commented
Stale PR

2021-04-15 23:59 UTC, closed without merging