Add flag to `mc replicate` for existing object replication
minio/mc pull request #3698
Opened 2021-04-21 06:41 UTC by poornas

Needs https://github.com/minio/minio-go/pull/1483/files
For https://github.com/minio/minio/pull/12109

2021-06-04 21:41 UTC, harshavardhana approved these changes

2021-06-11 10:20 UTC, vadmeste commented
@poornas could you fix conflicts here ?

2021-06-11 10:32 UTC, vadmeste reviewed
Some comments

2021-06-11 10:32 UTC, vadmeste commented on cmd/replicate-add.go
> +	fmt.Println("existing stat>", existingReplicationStatus)
Not needed

2021-06-11 10:32 UTC, vadmeste commented on cmd/replicate-reset.go
> +	Name:         "reset",
Maybe "resync" is a better name ?

2021-06-11 16:18 UTC, harshavardhana requested changes

2021-06-11 16:18 UTC, harshavardhana commented on cmd/replicate-reset.go
> +	Name:         "reset",
yeah resync is better word than `reset`

2021-06-11 16:54 UTC, poornas commented on cmd/replicate-reset.go
> +	Name:         "reset",
changed this

2021-06-11 18:26 UTC, kannappanr commented on cmd/replicate-resync.go
> +	return console.Colorize("replicateResyncMessage", fmt.Sprintf("Replication reset started for %s with ID %s", r.URL, r.ResetID))
`Replication reset started for` -> `Replication resync started for`

2021-06-11 19:08 UTC, kannappanr approved these changes
LGTM

2021-06-11 19:14 UTC, harshavardhana requested changes

2021-06-11 19:14 UTC, harshavardhana commented on cmd/admin-bucket-remote-add.go
> +	ResetBefore         time.Time     `json:"resetBeforeDate"`
If we are going to call it resync, let's rename everything properly

2021-06-12 18:04 UTC, harshavardhana requested changes

2021-06-12 18:04 UTC, harshavardhana commented on cmd/auto-complete.go
> +	"/replicate/reset":  s3Complete{deepLevel: 2},
```suggestion
	"/replicate/resync":  s3Complete{deepLevel: 2},
```

2021-06-12 18:04 UTC, harshavardhana commented on cmd/replicate-reset.go
> +	Name:         "reset",
```suggestion
	Name:         "resync",
```

2021-06-12 18:04 UTC, harshavardhana commented on cmd/replicate-reset.go
> +	Aliases:      []string{"resync"},
```suggestion
	Aliases:      []string{"reset"},
```

2021-06-12 18:04 UTC, harshavardhana commented on cmd/replicate-reset.go
> +	Usage:        "reset replication on previously replicated objects",
```suggestion
	Usage:        "re-replicate all previously replicated objects",
```

2021-06-12 18:04 UTC, harshavardhana commented on cmd/replicate-reset.go
> +  2. Reset server side replication for bucket "mybucket" for alias "myminio" for objects older than 60 days.
```suggestion
  2. Re-replicate all objects older than 60 days in "mybucket".
```

2021-06-12 18:04 UTC, harshavardhana commented on cmd/replicate-reset.go
> +EXAMPLES:
there is some tabbing issue here, looks like indentation is off from other commands

2021-06-12 18:04 UTC, harshavardhana commented on go.sum
>  github.com/minio/pkg v1.0.3 h1:tUhM6lG/BdNB0+5f2RbE4ifCAYwMs6cRJnZ/AY0WIeQ=
run `go mod tidy`

2021-06-13 01:01 UTC, harshavardhana approved these changes

2021-06-13 01:02 UTC, merged