Speedtest implementation
minio/mc pull request #3759
Opened 2021-07-21 23:52 UTC by krishnasrinivas

2021-07-29 21:33 UTC, krisis approved these changes

2021-07-29 22:13 UTC, poornas requested changes

2021-07-29 22:13 UTC, poornas commented on cmd/admin-speedtest.go
> +     {{.Prompt}} {{.HelpName}} --duration 20s --size 128MiB --concurrent 32
alias missing

2021-07-29 22:13 UTC, poornas commented on cmd/admin-speedtest.go
> +	}
need a validation to check if duration is > 0 to avoid panic

2021-07-30 01:11 UTC, kannappanr approved these changes
LGTM

2021-07-30 01:18 UTC, merged