Support autotuning of the workload for speedtest
minio/mc pull request #3777
Opened 2021-08-19 08:05 UTC by krishnasrinivas

2021-08-19 19:17 UTC, harshavardhana requested changes
@krishnasrinivas I thought we are going to do auto-tuning on the server side, not on the client?

2021-08-19 21:08 UTC, krishnasrinivas commented
@harshavardhana I think we did not discuss on the implementation details. I did it this way as it's a simpler approach to keep API and server side functionality simple and drive the tuning from client side.

2021-08-19 22:44 UTC, dvaldivia approved these changes
Tested. LGTM.
```
root@my-shell2:/# ./mc admin speedtest myminio
Running speedtest (autotune: true).........
MinIO 2021-08-17T20:53:08Z, 4 nodes, 28 drives
PUT: 1.4 GiB/s, 1012 objs/s
GET: 3.0 GiB/s, 3839 objs/s
```

2021-09-13 06:07 UTC, harshavardhana approved these changes

2021-09-15 06:29 UTC, merged