rb: Fix side wide removal of an alias
minio/mc pull request #3796
Opened 2021-09-14 12:13 UTC by vadmeste

rb --force --dangerous should remove all buckets under an alias. This
PR fixes a recent regression.

Depends on https://github.com/minio/mc/pull/3783

2021-09-17 12:18 UTC, klauspost commented
Can we add a regression test?

2021-09-17 15:30 UTC, harshavardhana approved these changes

2021-09-18 16:17 UTC, harshavardhana requested changes

2021-09-18 16:17 UTC, harshavardhana commented on .github/workflows/go.yml
> +          export SERVER_ENDPOINT=localhost:9000 ACCESS_KEY=minioadmin SECRET_KEY=minioadmin ENABLE_HTTPS=1
Shouldn't this export be in multiple lines?

2021-09-18 16:17 UTC, harshavardhana commented on .github/workflows/go.yml
> +          mkdir -p ~/.minio/certs/ && openssl req -x509 -newkey rsa:1024 -keyout ~/.minio/certs/private.key -out ~/.minio/certs/public.crt -days 7 -nodes -subj '/CN=localhost'
You can get the certs from minio-go repo if necessary for localhost keys @vadmeste Or commit the certs into mc repo.

2021-09-18 16:17 UTC, harshavardhana commented on functional-tests.sh
> +    curl -ksSg --output "${object_name}.downloaded" -X GET "$download_url"
Let's just trust the system?

2021-09-18 16:17 UTC, harshavardhana commented on .github/workflows/go.yml
> +          mkdir -p ~/.minio/certs/ && openssl req -x509 -newkey rsa:1024 -keyout ~/.minio/certs/private.key -out ~/.minio/certs/public.crt -days 7 -nodes -subj '/CN=localhost'
Or better use mkcert in batch mode to generate and trust the certs

2021-09-18 16:17 UTC, harshavardhana commented on functional-tests.sh
> +    curl -ksSg --output "${object_name}.downloaded" -X GET "$download_url"
You can avoid curl -k once certs trusted with mkcert

2021-09-20 15:44 UTC, harshavardhana approved these changes

2021-09-21 10:22 UTC, klauspost approved these changes
LGTM 👍🏼

2021-10-06 16:56 UTC, merged