admin info: Show 'OK' in yellow when offline networks/disks
minio/mc pull request #3814
Opened 2021-09-29 13:21 UTC by vadmeste

In mc admin info output, it is better to show 'OK' status in yellow and
not in green when there is a failed disk or a failed network link so it
is easier for users to detect something wrong.

2021-09-29 13:38 UTC, klauspost approved these changes
LGTM

2021-10-05 06:21 UTC, harshavardhana requested changes

2021-10-05 06:21 UTC, harshavardhana commented on cmd/admin-info.go
> +			fmt.Println(len(srv.Disks))
is this expected log? @vadmeste

2021-10-05 07:53 UTC, vadmeste commented on cmd/admin-info.go
> +			fmt.Println(len(srv.Disks))
```suggestion
			fmt.Println(len(srv.Disks))

```

2021-10-05 07:54 UTC, harshavardhana approved these changes

2021-10-06 00:00 UTC, merged