Use latest version of madmin-go
minio/mc pull request #3866
Opened 2021-11-15 06:49 UTC by anjalshireesh

It contains a new field `TLSInfoAvailable` which will get added under
the `tls` node in health report, helping `health-analyzer` perform the
TLS related checks more reliably.

2021-11-15 06:59 UTC, harshavardhana requested changes

2021-11-15 06:59 UTC, harshavardhana commented on go.mod
> +	github.com/minio/madmin-go v1.1.14-0.20211112204931-d450d5fdd7e1
```suggestion
	github.com/minio/madmin-go v1.1.14
```

2021-11-15 07:07 UTC, harshavardhana requested changes

2021-11-15 07:07 UTC, harshavardhana commented on go.sum
> +github.com/minio/madmin-go v1.1.14/go.mod h1:Iu0OnrMWNBYx1lqJTW+BFjBMx0Hi0wjw8VmqhiOs2Jo=
```
go mod tidy
```

is perhaps needed

2021-11-15 07:22 UTC, anjalshireesh commented on go.sum
> +github.com/minio/madmin-go v1.1.14/go.mod h1:Iu0OnrMWNBYx1lqJTW+BFjBMx0Hi0wjw8VmqhiOs2Jo=
Done

2021-11-15 07:31 UTC, harshavardhana approved these changes

2021-11-18 08:44 UTC, harshavardhana approved these changes

2021-11-18 22:30 UTC, merged