Update admin policy/user commands after policy info response change
minio/mc pull request #3877
Opened 2021-12-01 19:57 UTC by donatello

2021-12-03 00:21 UTC, harshavardhana requested changes

2021-12-03 00:21 UTC, harshavardhana commented on go.sum
> +github.com/minio/madmin-go v1.1.17-0.20211202194304-c4be92551063/go.mod h1:Iu0OnrMWNBYx1lqJTW+BFjBMx0Hi0wjw8VmqhiOs2Jo=
perhaps `go mod tidy` is missing

2021-12-03 01:23 UTC, donatello commented on go.sum
> +github.com/minio/madmin-go v1.1.17-0.20211202194304-c4be92551063/go.mod h1:Iu0OnrMWNBYx1lqJTW+BFjBMx0Hi0wjw8VmqhiOs2Jo=
Fixed

2021-12-06 16:26 UTC, krisis approved these changes

2021-12-08 17:04 UTC, vadmeste commented
@donatello isn't this change suppoed to work with older versions of MinIO ? 

Currently `mc admin policy info myminio readwrite` shows null output with minio master

2021-12-08 17:37 UTC, donatello commented
> @donatello isn't this change suppoed to work with older versions of MinIO ? 


Ah ok, I thought it would be upgraded with minio. I can try the older api and then fail. Will send a fix.

2021-12-08 18:57 UTC, donatello commented
@vadmeste Fixed, PTAL.

2021-12-11 14:16 UTC, vadmeste approved these changes
LGTM

2021-12-11 16:32 UTC, kannappanr approved these changes
LGTM

2021-12-11 17:04 UTC, merged