Add admin replicate status command
minio/mc pull request #3887
Opened 2021-12-11 00:55 UTC by poornas

2022-01-05 23:36 UTC, harshavardhana commented
@poornas please fix conflicts.

2022-01-06 01:03 UTC, harshavardhana requested changes

2022-01-06 01:03 UTC, harshavardhana commented on cmd/admin-replicate-status.go
> +  1. Get Site Replication status:
```suggestion
  1. Display Site Replication status:
```

2022-01-06 01:15 UTC, harshavardhana approved these changes

2022-01-06 21:27 UTC, donatello approved these changes

2022-01-06 21:50 UTC, merged