Add `admin replicate remove` command to allow removal of sites
minio/mc pull request #3919
Opened 2022-01-14 01:57 UTC by poornas

2022-01-14 13:30 UTC, klauspost commented on cmd/admin-replicate-remove.go
> +		if !ctx.IsSet("force") {
Always having to add `--force` makes it lose its meaning.

To be honest I don't really see a need for it. It is not destructive. Sure, you lose the config, but no data is ever in jeopardy. When you specify `--all` it can't really be a surprise it removes all.

2022-01-14 18:20 UTC, poornas commented on cmd/admin-replicate-remove.go
> +		if !ctx.IsSet("force") {
With `remove`, the site that is removed cannot rejoin site replication with `mc admin replicate add` because there is a constraint requiring the clusters to be empty at the time of joining site replication. In most situations this would not be the case, hence the need for --force.  

There is a plan to add suspend|resume as a alternate where the intent is just to stop participation in site replication temporarily

2022-02-02 02:31 UTC, harshavardhana commented on cmd/admin-replicate-remove.go
> +		if !ctx.IsSet("force") {
Force is more like a confirmation without throwing users y/n - questions. Since they need to mean it by typing `--force`.  But perhaps in future we can add "suspend/resume" that happens without --force, it means like a `soft remove` instead of `hard remove`.

2022-02-02 02:34 UTC, harshavardhana requested changes

2022-02-02 02:34 UTC, harshavardhana commented on cmd/admin-replicate-remove.go
> +     {{.Prompt}} {{.HelpName}} minio2 alpha baker
This needs to have `--force`

2022-02-02 02:34 UTC, harshavardhana commented on cmd/admin-replicate-remove.go
> +		if !ctx.IsSet("force") {
input validation should be in a function to follow most commands in `mc` style as `checkAdminReplicationRemoveStatusSyntax()`  function name.

2022-02-02 02:34 UTC, harshavardhana commented on cmd/admin-replicate-remove.go
> +	return console.Colorize("UserMessage", i.Status)
```suggestion
	return console.Colorize("UserMessage", i.Status)
```

We should word it like what all sites were removed?

2022-02-04 07:38 UTC, harshavardhana commented
PTAL @poornas

2022-02-04 10:56 UTC, klauspost approved these changes
Nothing that isn't already mentioned 👍🏼

2022-02-04 21:29 UTC, poornas commented on cmd/admin-replicate-remove.go
> +	return console.Colorize("UserMessage", i.Status)
the Status here is sent from the server and will have more detailed info on which sites were not removed, if any

2022-02-04 22:52 UTC, harshavardhana commented on cmd/admin-replicate-remove.go
> +	return console.Colorize("UserMessage", i.Status)
Is it not possible to show what was asked to be removed since you get the input for the site name?

2022-02-05 01:01 UTC, harshavardhana requested changes

2022-02-05 01:01 UTC, harshavardhana commented on cmd/admin-replicate-remove.go
> +	return console.Colorize("UserMessage", fmt.Sprintf("%s were removed successfully from site replication", strings.Join(i.sites, ", ")))
in case of when no sites are given do you want to say `all sites were removed` ?

2022-02-05 01:04 UTC, poornas commented on cmd/admin-replicate-remove.go
> +	return console.Colorize("UserMessage", fmt.Sprintf("%s were removed successfully from site replication", strings.Join(i.sites, ", ")))
syntax validation would have caught that

2022-02-05 01:09 UTC, harshavardhana commented on cmd/admin-replicate-remove.go
> +	return console.Colorize("UserMessage", fmt.Sprintf("%s were removed successfully from site replication", strings.Join(i.sites, ", ")))
how what happens when I pass `--all` @poornas ?

2022-02-11 02:29 UTC, harshavardhana approved these changes

2022-02-11 02:50 UTC, merged