tier-info: Add bar charts for 24hr dailys tier-stats
minio/mc pull request #3928
Opened 2022-01-21 01:08 UTC by krisis

Depends on https://github.com/minio/minio/pull/13782

2022-01-26 23:15 UTC, harshavardhana requested changes

2022-01-26 23:15 UTC, harshavardhana commented on cmd/admin-tier-info-ui.go
> +package cmd
license is missing @krisis

2022-02-13 23:36 UTC, harshavardhana approved these changes

2022-02-13 23:36 UTC, harshavardhana commented
PTAL @krisis at the conflicts

2022-02-17 20:57 UTC, poornas requested changes

2022-02-17 20:57 UTC, poornas commented on cmd/admin-tier-info.go
> +  2. Print per-tier statistcs of given tier
```suggestion
  2. Print per-tier statistics of given tier
```

2022-02-22 19:24 UTC, poornas approved these changes

2022-02-24 20:51 UTC, merged