Change `mc admin replicate status` ui
minio/mc pull request #3936
Opened 2022-01-25 22:56 UTC by poornas

to have additional filters

Needs https://github.com/minio/madmin-go/pull/67

2022-01-28 22:52 UTC, harshavardhana approved these changes

2022-01-28 22:54 UTC, harshavardhana commented
```
Running lint check
Error: cmd/admin-replicate-status.go:130: File is not `gofumpt`-ed (gofumpt)
	var coloredDot = console.Colorize("Status", dot)
Error: cmd/admin-replicate-status.go:324: File is not `gofumpt`-ed (gofumpt)
}
Error: cmd/admin-replicate-status.go:347: File is not `gofumpt`-ed (gofumpt)
	var coloredDot = console.Colorize("Status", dot)
Error: make: *** [Makefile:38: lint] Error 1
Error: Process completed with exit code 2.
```

2022-01-30 07:33 UTC, kannappanr commented
Please resolve the conflicts

2022-01-31 20:07 UTC, harshavardhana requested changes

2022-01-31 20:07 UTC, harshavardhana commented on go.mod
> +	github.com/minio/madmin-go v1.2.9
```suggestion
	github.com/minio/madmin-go v1.3.0
```

2022-01-31 21:08 UTC, harshavardhana approved these changes

2022-02-01 23:51 UTC, merged