WIP Add usage information to output if no arguments passed to mc alias set
minio/mc pull request #3963
Opened 2022-02-08 00:07 UTC by jinapurapu

Addresses https://github.com/miniohq/engineering/issues/269

2022-02-08 01:35 UTC, harshavardhana requested changes

2022-02-08 01:35 UTC, harshavardhana commented on cmd/alias-set.go
> +			}
If there are configured endpoints that are not reachable this command will never return @jinapurapu - I don't think this is a feasible behavior.

2022-02-08 20:44 UTC, harshavardhana commented
is this still a WIP ? @jinapurapu

2022-02-08 22:09 UTC, jinapurapu commented
No, I have updated it, it is working now.

2022-02-08 22:16 UTC, harshavardhana approved these changes

2022-02-09 10:05 UTC, klauspost approved these changes

2022-02-09 11:14 UTC, merged