extend 'mc support inspect --export=json' to export JSON directly
minio/mc pull request #3981
Opened 2022-02-14 07:15 UTC by harshavardhana

this is essentially same code at
https://github.com/minio/minio/tree/master/docs/debugging/xl-meta

--export option provides exporting 'xl.meta' information as 'json'
or export the inlined-data 'json' that represents 'version-id' and
the corresponding size of the inlined-data.

This essentially now provides full visibility of the inspect data
that is captured, extracts and converts them into some parseable
JSON.

2022-02-14 08:55 UTC, klauspost approved these changes

2022-02-15 05:29 UTC, poornas requested changes

2022-02-15 05:29 UTC, poornas commented on cmd/support-inspect.go
> +	fatalIf(probe.NewError(moveFile(tmpFile.Name(), downloadPath)), "Unable rename downloaded data, file exists at %s", tmpFile.Name())
```suggestion
	fatalIf(probe.NewError(moveFile(tmpFile.Name(), downloadPath)), "Unable to rename downloaded data, file exists at %s", tmpFile.Name())
```

2022-02-15 05:29 UTC, poornas commented on cmd/inspect-export.go
> +// Copyright (c) 2015-2021 MinIO, Inc.
```suggestion
// Copyright (c) 2015-2022 MinIO, Inc.
```

2022-02-15 07:01 UTC, poornas approved these changes

2022-02-15 09:52 UTC, merged