Error handling for remove alias request if alias not found
minio/mc pull request #4017
Opened 2022-03-11 21:34 UTC by jinapurapu

Previously, `mc alias remove thisalias` would return a success message even if `thisalias` was not an existing alias. This checks if the requested alias is present in the configuration file, and if not, throws an appropriate error message.

2022-03-30 21:16 UTC, harshavardhana requested changes

2022-03-30 21:16 UTC, harshavardhana commented on cmd/alias-remove.go
>  	conf, err := loadMcConfig()
We could just add this here

```
        hostConfig := mustGetHostConfig(alias)
        if hostConfig == nil {
                fatalIf(errInvalidAliasedURL(alias), "No such alias `"+alias+"` found.")
                return nil
        }
```

2022-04-01 02:27 UTC, harshavardhana requested changes

2022-04-01 02:27 UTC, harshavardhana commented on cmd/alias-remove.go
> +	fatalIf(err.Trace(alias), alias+" not found in the configuration file. Please confirm the alias name you are trying to remove. You can use mc alias list to view a list of all aliases configured.")
we already exit inside isAliasIn() there is no reason for this function to return a `nil` and this fatalIf() will never be called.

```
func aliasMustExist(alias string) {
hostConfig := mustGetHostConfig(alias)
	if hostConfig == nil {
		fatalIf(errInvalidAliasedURL(alias), "No such alias `"+alias+"` found.")
}
```

This is all we need

2022-04-05 15:26 UTC, klauspost approved these changes

2022-04-07 20:43 UTC, harshavardhana commented on cmd/alias-remove.go
> +	fatalIf(err.Trace(alias), alias+" not found in the configuration file. Please confirm the alias name you are trying to remove. You can use mc alias list to view a list of all aliases configured.")
@jinapurapu

2022-04-11 20:26 UTC, harshavardhana approved these changes

2022-04-11 20:26 UTC, merged