Make sure to print `mc rm` dry run message
minio/mc pull request #4033
Opened 2022-03-31 19:18 UTC by poornas

2022-03-31 22:57 UTC, harshavardhana requested changes
On a versioned bucket this won't make sense what will dry-run show for a versioned bucket ?

2022-04-01 04:17 UTC, kannappanr commented
> On a versioned bucket this won't make sense what will dry-run show for a versioned bucket ?

```
$ mc rm play/test -r --dry-run --force
DRYRUN: Removing  /test/policy.json

$ mc rm play/test -r --dry-run --force --versions
DRYRUN: Removing  /test/policy.json version: null

$ mc rm play/testlock -r --dry-run --force  --versions
DRYRUN: Removing  /testlock/prefix/prefix/ version: 5dfd97b9-8028-4577-8303-fae4                                                                             6a293055
DRYRUN: Removing  /testlock/prefix/prefix/ version: 067ef3cd-a5a3-4bda-8499-c1f4                                                                             1d80153c
DRYRUN: Removing  /testlock/prefix/prefix/issue version: 4fbaf587-d8eb-4a96-9ed3                                                                             -c2b086ef3832

```

2022-04-01 04:54 UTC, kannappanr approved these changes

2022-04-01 06:15 UTC, poornas commented
> On a versioned bucket this won't make sense what will dry-run show for a versioned bucket ?
With versioned bucket, it is going to be like this
```
mc rm sitea/bucket -r --versions --force --fake 
DRYRUN: Removing  /bucket/copy-11536 version: 01e6438d-041a-46ee-af30-2c2319ae9fde
mc rm sitea/bucket -r  --force --fake 
DRYRUN: Removing  /bucket/copy-11536
```

2022-04-01 08:19 UTC, merged