Update documentation for --older/newer-than flags
minio/mc pull request #4039
Opened 2022-04-04 09:22 UTC by ndoornekamp

The current documentation for the --older-than and --newer-than flags suggested that the value for these flags should be an integer specifying a number of days, while it should be a duration string (e.g. 7d10h31s).

2022-04-07 20:43 UTC, donatello approved these changes

2022-04-07 20:44 UTC, harshavardhana approved these changes

2022-04-07 20:44 UTC, donatello commented
Could you also update the help strings for in the go file @ndoornekamp ?

2022-04-07 20:48 UTC, donatello requested changes
Need changes to help strings in sources files too:

```
cmd/mv-main.go
40:			Name:  "older-than",
41-			Usage: "move objects older than L days, M hours and N minutes",
42-		},
--
44:			Name:  "newer-than",
45-			Usage: "move objects newer than L days, M hours and N minutes",
46-		},

cmd/rm-main.go
84:			Name:  "older-than",
85-			Usage: "remove objects older than L days, M hours and N minutes",
86-		},
--
88:			Name:  "newer-than",
89-			Usage: "remove objects newer than L days, M hours and N minutes",
90-		},

cmd/replicate-reset-start.go
37:		Name:  "older-than",
38-		Usage: "replicate back objects older than n days",
39-	},

cmd/mirror-main.go
100:			Name:  "older-than",
101-			Usage: "filter object(s) older than L days, M hours and N minutes",
102-		},
--
104:			Name:  "newer-than",
105-			Usage: "filter object(s) newer than L days, M hours and N minutes",
106-		},

cmd/find-main.go
48:			Name:  "newer-than",
49-			Usage: "match all objects newer than L days, M hours and N minutes",
50-		},
--
52:			Name:  "older-than",
53-			Usage: "match all objects older than L days, M hours and N minutes",
54-		},

cmd/cp-main.go
54:			Name:  "older-than",
55-			Usage: "copy objects older than L days, M hours and N minutes",
56-		},
--
58:			Name:  "newer-than",
59-			Usage: "copy objects newer than L days, M hours and N minutes",
60-		},
```

2022-04-16 14:35 UTC, harshavardhana approved these changes

2022-04-16 15:08 UTC, ndoornekamp commented
@harshavardhana @donatello What's the next step for this? It looks like it's ready to be merged, but I'm not authorized to do that.

2022-04-16 15:10 UTC, merged