Update examples for admin-config-reset
minio/mc pull request #4160
Opened 2022-07-20 22:13 UTC by taran-p

Update examples to reflect minio server-side features

2022-07-22 21:08 UTC, donatello requested changes
The USAGE string should say to indicate an optional set of sub-keys may be given:

```
{{.HelpName}} TARGET [CONFIG-KEY...]
```

2022-07-22 21:12 UTC, donatello requested changes
Also, we need to add some validation to avoid this type of error:

```
$ mc admin config reset myminio scanner max_wait=30s
mc: <ERROR> Unable to reset 'scanner max_wait=30s' on the server: key max_wait=30s doesn't exist.
```

In this case, `mc` should validate the command and say that new settings may not be provided for sub-system keys.

2022-07-22 22:29 UTC, harshavardhana approved these changes

2022-08-04 20:03 UTC, donatello approved these changes

2022-08-06 03:29 UTC, merged