sort by Rx or Tx in admin top api command
minio/mc pull request #4199
Opened 2022-08-10 12:27 UTC by sinhaashish

```

2022-08-10 14:45 UTC, harshavardhana requested changes

2022-08-10 14:45 UTC, harshavardhana commented on cmd/top-api-spinner.go
> -			whiteStyle.Render(humanize.IBytes(stats.loadAPIBytesRX())),
Is removal of coloring expected here ?

2022-08-10 14:45 UTC, harshavardhana commented on cmd/top-api-spinner.go
> -			whiteStyle.Render(humanize.IBytes(stats.loadAPIBytesRX())),
You should sort this before if necessary, otherwise it's simply expensive to parse the strings again and again.

2022-08-22 12:08 UTC, klauspost reviewed
`--sort=RX` would be cleaner IMO. Also eliminates the possibility of both being selected, and you can add `CALLS` and `ERRORS` as well.

2022-09-28 03:50 UTC, closed without merging