Introduce disk top IO
minio/mc pull request #4201
Opened 2022-08-10 14:46 UTC by vadmeste

This shows IO stats of MinIO backend disks

Depends on https://github.com/minio/madmin-go/pull/111

2022-08-10 14:47 UTC, harshavardhana commented
How does it look do you have an asciinema?

2022-08-10 14:49 UTC, harshavardhana requested changes

2022-08-10 14:49 UTC, harshavardhana commented on cmd/admin-top-disk.go
> +	Usage:           "Show disk stats in real-time",
```suggestion
	Usage:           "show current disk statistics",
```

2022-08-10 15:04 UTC, vadmeste commented
> How does it look do you have an asciinema?

https://asciinema.org/a/hDH7gZXzYK5Q9BIuvK0XlVUeW

I actually failed to find 4 different disks. Overall there is sorting by column, disk usage, tps, read/write speed, await and utilisation.

There is also left right arrow to change the current pool

2022-08-10 15:10 UTC, harshavardhana commented
> I actually failed to find 4 different disks. Overall there is sorting by column, disk usage, tps, read/write speed, await and utilisation.

Well you can do `losetup`  @vadmeste

2022-08-22 17:51 UTC, harshavardhana approved these changes

2022-08-22 17:52 UTC, merged