Use 'less' for help output
minio/mc pull request #4245
Opened 2022-09-13 09:54 UTC by vadmeste

## Description
If /usr/bin/less exists, use it when mc starts to print the help message.

The initialization of less binary is lazy and happens in the first help write invoked by minio/cli package.

Ensure mc waits until the user exits the less binary.

## Motivation and Context
Add pagination when printing long help message

## How to test this PR?
mc cp -h

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

2022-09-13 10:26 UTC, klauspost commented
@vadmeste Would you mind if I try to implement without invoking less?

2022-09-13 10:38 UTC, vadmeste commented
> @vadmeste Would you mind if I try to implement without invoking less?

No problem, do you know any good library for that ? also I found it this PR doesn't work in some cases, unfortunately the cli library calls os.Exit() in certain cases, this is maybe not easy to implement

2022-09-13 10:50 UTC, klauspost commented
Yeah, `os.Exit` is always going to be a problem. So this only for help (for now?)

While a full 'less' would be great, maybe just paging would be fine.

External programs are always going to be flaky, so while it has the upside of all the "less" features, if they need that then `mc --help|less` is the way to go.

2022-09-15 09:30 UTC, vadmeste commented
> Rather than using less you can use this https://github.com/charmbracelet/bubbletea/tree/master/examples/pager @vadmeste

Yes, I didn't see this when I went through their docs, will try it out

2022-09-15 20:58 UTC, vadmeste commented
I made some progress, the code currently is little bit complex because I had to connect cli with bubbletea but overall it is fine, can you test this @harshavardhana before I make the remaining changes ? hopefully no surprises after that

2022-09-15 22:53 UTC, harshavardhana commented
It works fine @vadmeste however we have to show how to `quit` at the bottom page otherwise users won't know how to quit the pager.

2022-09-16 07:40 UTC, vadmeste commented
> It works fine @vadmeste however we have to show how to quit at the bottom page otherwise users won't know how to quit the pager.

okay, there are still more edge cases that I need to address, they should be fixed today

2022-09-19 09:38 UTC, vadmeste commented
This PR https://github.com/minio/cli/pull/9/files is also needed. Otherwise all of this won't work :)

2022-09-22 21:07 UTC, harshavardhana requested changes

2022-09-22 21:07 UTC, harshavardhana commented on cmd/term-pager.go
> +package cmd
license header missing @vadmeste

2022-09-22 21:07 UTC, harshavardhana commented on main.go
> +		os.Exit(1)
```suggestion
		console.Fatalln(e)
```

2022-09-23 17:19 UTC, harshavardhana requested changes

2022-09-23 17:19 UTC, harshavardhana commented on go.mod
> +	github.com/minio/cli v1.23.1-0.20220921164421-38105e9ed822
tagged v1.24.0 @vadmeste

2022-09-27 22:44 UTC, harshavardhana commented
PTAL at the conflict @vadmeste

2022-09-28 15:09 UTC, harshavardhana approved these changes

2022-09-28 18:28 UTC, merged

2022-10-08 21:49 UTC, zeeZ commented
Is there an option included to disable this?

It's pretty cumbersome if the help output disappears while you're trying to cobble together a command with multiple flags and one can't look at the output history because it disappears with the pager.

`mc cp -h | cat` is a dumb workaround.

2022-10-09 00:15 UTC, harshavardhana commented
We are going to fix the pager for it to stay the output..

2022-10-09 13:58 UTC, vadmeste commented
> Is there an option included to disable this?

@zeeZ I think you want this PR, https://github.com/minio/mc/pull/4289, it keeps the help screen after quitting it