Add number of offline disks in heal info summary
minio/mc pull request #4305
Opened 2022-10-17 15:58 UTC by vadmeste

## Description
Currently healing information accuracy relies on the availability on the node. Instead of saying with confidence that there is no healing is going on, add a warning that there are some disks which are not reachable.

## Motivation and Context
Better UX

## How to test this PR?
- Run a cluster of 4 nodes
- Kill one node and run `mc admin heal <alias>` and `mc admin heal -v <alias>`

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

2022-10-17 16:46 UTC, harshavardhana requested changes

2022-10-17 16:46 UTC, harshavardhana commented on cmd/admin-heal.go
> +			healPrettyMsg += fmt.Sprintf(", though %d offline/corrupted disk(s) found.", problematicDisks)
```suggestion
			healPrettyMsg += fmt.Sprintf(", though %d offline disk(s) found.", problematicDisks)
```

2022-10-17 16:46 UTC, harshavardhana commented on cmd/admin-heal.go
> +		healPrettyMsg += fmt.Sprintf("%d offline or corrupted disk(s) found.", problematicDisks)
```suggestion
		healPrettyMsg += fmt.Sprintf("%d offline disk(s) found.", problematicDisks)
```

2022-10-17 16:46 UTC, harshavardhana commented on cmd/admin-heal.go
> +				if disk.State != madmin.DriveStateUnformatted {
shouldn't this be in oneline?

```
if disk.State != madmin.DriveStateOk && disk.State != madmin.DriveStateUnformatted {
```

2022-10-17 19:32 UTC, harshavardhana approved these changes

2022-10-18 15:44 UTC, prakashsvmx approved these changes

2022-10-18 16:01 UTC, merged