Print 'Cancel upon user request' when the global context is cancelled
minio/mc pull request #4406
Opened 2022-12-13 15:20 UTC by vadmeste

## Description
The code creates new context and cancels them and it is not 
correct to show 'Cancel upon user request' when an error 
is context.Cancelled.

Fix this by requiring globalContext error to be context.Cancelled. 
The global context is only cancelled after receiving a signal.

## Motivation and Context
Fix this error message: 'Cancel upon user request' error message
when the user did not really kill mc

## How to test this PR?
Not trivial

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

2022-12-13 16:25 UTC, harshavardhana requested changes

2022-12-13 16:25 UTC, harshavardhana commented on cmd/error.go
> +		if globalContext.Err() == context.Canceled {
You can still use errors.Is()

2022-12-14 12:21 UTC, harshavardhana approved these changes

2022-12-16 17:37 UTC, krisis approved these changes

2022-12-17 07:26 UTC, merged