info: Show drive/server tolerance
minio/mc pull request #4426
Opened 2022-12-27 14:03 UTC by vadmeste

## Description

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

2022-12-27 17:59 UTC, harshavardhana requested changes

2022-12-27 17:59 UTC, harshavardhana commented on cmd/admin-info.go
> +			msg += fmt.Sprintf(", Drives tolerance: %s, Servers tolerance: %s",
```suggestion
			msg += fmt.Sprintf(", Drive(s) tolerance: %s, Server(s) tolerance: %s",
```

2022-12-27 17:59 UTC, harshavardhana commented on cmd/admin-info.go
> +			msg += fmt.Sprintf(", Drives tolerance: %s, Servers tolerance: %s",
```suggestion
			msg += fmt.Sprintf(", Drive(s) tolerance: %s, Server(s) tolerance: %s",
```

2022-12-27 18:00 UTC, harshavardhana requested changes

2022-12-27 18:00 UTC, harshavardhana commented on cmd/admin-info.go
> +func toleranceInfoText(remainingItems int) string {
```suggestion
func toleranceInfoText(tolerance int) string {
```

2022-12-27 18:00 UTC, harshavardhana commented on cmd/admin-info.go
> +	if remainingItems < 0 {
```suggestion
	if tolerance < 0 {
```

2023-04-03 10:42 UTC, vadmeste commented
I need to review this. This PR doesn't work well when there is more than 16 nodes

2023-09-17 19:51 UTC, closed without merging