Add trace for ilm call type
minio/mc pull request #4538
Opened 2023-04-06 16:36 UTC by poornas

## Description

## Motivation and Context
Allow tracing ilm operations

## How to test this PR?
Needs https://github.com/minio/madmin-go/pull/186

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

2023-04-06 18:06 UTC, harshavardhana requested changes

2023-04-06 18:06 UTC, harshavardhana commented on go.mod
> +replace github.com/minio/madmin-go/v2 => github.com/poornas/madmin-go/v2 v2.0.0-20230406162832-ee76020dca2b
please madmin-go to the newer release that you want @poornas `git tag` and `git push -u origin --tags`

2023-04-06 20:23 UTC, vadmeste reviewed
One comment, LGTM otherwise

2023-04-06 20:23 UTC, vadmeste commented on go.mod
> +	github.com/minio/madmin-go/v2 v2.0.19-0.20230406175749-1404a84d1612
There is v2.0.19 now

2023-04-06 20:38 UTC, krisis approved these changes

2023-04-08 15:25 UTC, klauspost approved these changes

2023-04-08 18:37 UTC, harshavardhana approved these changes

2023-04-08 18:37 UTC, merged