Load Subnet proxy and API key from the env if found
minio/mc pull request #4557
Opened 2023-04-24 14:31 UTC by vadmeste

## Description

Avoid sending calls to MinIO cluser to fetch for Subnet proxy
 and API key if specified in the environment

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

2023-04-25 18:41 UTC, harshavardhana requested changes

2023-04-25 18:41 UTC, harshavardhana commented on cmd/subnet-utils.go
> +			EnvVar: "_MC_SUBNET_API_KEY",
```suggestion
			EnvVar: "MC_SUBNET_API_KEY",
```

2023-04-25 18:41 UTC, harshavardhana commented on cmd/subnet-utils.go
> +	if env, ok := os.LookupEnv("_MC_SUBNET_PROXY_URL"); ok {
```suggestion
	if env, ok := os.LookupEnv("MC_SUBNET_PROXY_URL"); ok {
```

2023-04-25 18:41 UTC, harshavardhana commented on cmd/support-profile.go
> +			successClr.Printf("Profiling data are saved locally at '%s'\n", profileFile)
```suggestion
			successClr.Printf("Saving profiling data locally at '%s'\n", profileFile)
```

2023-04-26 05:23 UTC, anjalshireesh approved these changes
LGTM, minor nit.

2023-04-26 05:23 UTC, anjalshireesh commented on cmd/subnet-utils.go
> +		proxy, supported = getKeyFromSubnetConfig(alias, "proxy")
The comment on line#305 should also move here

2023-04-26 06:49 UTC, harshavardhana commented on cmd/subnet-utils.go
> +		proxy, supported = getKeyFromSubnetConfig(alias, "proxy")
```suggestion
	        // get the subnet proxy config from MinIO if available
		proxy, supported = getKeyFromSubnetConfig(alias, "proxy")
```

2023-04-26 06:49 UTC, harshavardhana commented on cmd/subnet-utils.go
>  	// get the subnet proxy config from MinIO if available
```suggestion
```

2023-05-09 01:41 UTC, dormanze approved these changes
LGTM

2023-05-09 16:15 UTC, harshavardhana commented
@vadmeste PTAL at CI failures

2023-05-09 17:11 UTC, harshavardhana approved these changes

2023-05-09 17:11 UTC, merged