Added option `--exclude-folders`
minio/mc pull request #4566
Opened 2023-05-08 07:58 UTC by shtripat

## Description
This flag works in conjunction with `--recursive` and sets tags for all the bucket objects minus the subdirs.

## Motivation and Context
User should be able to set tags for all the objects of the bucket excluding the subdirs, at once.

## How to test this PR?
- Create a bucket which contains few object and subdirs (with objects under them) as well.
- `mc tag set ALIAS/BUCKET "key=val" --exclude-folders --recursive`

The tags should be set for top level bucket objects only and not the subdir objects.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

2023-10-27 14:03 UTC, zveinn approved these changes
Remember to request a documentation update when/if this gets merged

2024-01-10 23:28 UTC, harshavardhana requested changes

2024-01-10 23:28 UTC, harshavardhana commented on cmd/tag-set.go
> +  7. Assign tags to all the objects of bucket, exclusing subdirs
```suggestion
  7. Assign tags to all the objects on a bucket, excluding folders
```

2024-01-10 23:28 UTC, harshavardhana commented on cmd/tag-set.go
> +		fatalIf(errDummy().Trace(), "Flag --exclude-folders can be used with --recursive only")
```suggestion
		fatalIf(errDummy().Trace(), "'--exclude-folders' must be used with --recursive only")
```

2024-01-11 05:49 UTC, harshavardhana approved these changes

2024-01-11 05:49 UTC, merged