heal: Add --update-parity flag to change the parity of one object
minio/mc pull request #4594
Opened 2023-06-08 11:15 UTC by vadmeste

## Description

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

2023-06-08 18:40 UTC, harshavardhana approved these changes

2023-06-08 18:40 UTC, harshavardhana commented
> One object only?

It does recursively apply to all, the PR title is misleading @klauspost

2023-06-09 10:01 UTC, klauspost requested changes
I guess this should be changed as well, then.

2023-06-09 10:01 UTC, klauspost commented on cmd/admin-heal.go
> +		Usage: "Update the parity of an object with the new server parity configuration",
```suggestion
		Usage: "Update the parity of objects with the new server parity configuration",
```

2023-06-09 18:35 UTC, harshavardhana requested changes

2023-06-09 18:35 UTC, harshavardhana commented on cmd/admin-heal.go
> +		Usage: "Update the parity of objects with the new server parity configuration",
```suggestion
		Usage: "Update the parity of object(s) with the new server parity configuration",
```

2023-06-09 18:35 UTC, harshavardhana approved these changes

2023-06-12 09:52 UTC, klauspost approved these changes

2023-06-12 18:19 UTC, closed without merging