support site replication
minio/mc pull request #4608
Opened 2023-06-20 15:17 UTC by jiuker

## Description

support site replication

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

2023-06-20 18:40 UTC, harshavardhana requested changes

2023-06-20 18:40 UTC, harshavardhana commented on cmd/support-perf-site-replication.go
> +// Copyright (c) 2022 MinIO, Inc.
```suggestion
// Copyright (c) 2023 MinIO, Inc.
```

2023-06-28 04:14 UTC, shtripat commented
Do we need an active site replication to test the change?

2023-07-05 17:46 UTC, harshavardhana approved these changes

2023-07-05 17:46 UTC, harshavardhana commented
> Do we need an active site replication to test the change?

yes you need a `site` replicated setup to test this change.

2023-07-05 18:19 UTC, poornas commented
```
➜  mc git:(support_site_replication) mc support perf site-replication sitea --airgap --dev

SiteReplication: ∙●∙

ENDPOINT	RX    	TX
...     	-- MiB	-- MiB
Caught panic:

runtime error: integer divide by zero

Restoring terminal...

goroutine 31 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	runtime/debug/stack.go:16 +0x1c
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
	github.com/charmbracelet/bubbletea@v0.23.2/tea.go:402 +0x8c
panic({0x10131f560, 0x101c65720})
	runtime/panic.go:890 +0x258
github.com/minio/mc/cmd.(*speedTestUI).View(0x1400052e790)
	github.com/minio/mc/cmd/speedtest-spinner.go:255 +0x280c
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0x1400052e840, {0x10149c0d0?, 0x1400052e790?}, 0x0?)
	github.com/charmbracelet/bubbletea@v0.23.2/tea.go:345 +0x5c8
github.com/charmbracelet/bubbletea.(*Program).Run(0x1400052e840)
	github.com/charmbracelet/bubbletea@v0.23.2/tea.go:465 +0x6b0
github.com/minio/mc/cmd.mainAdminSpeedTestSiteReplications.func2()
	github.com/minio/mc/cmd/support-perf-site-replication.go:86 +0x28
created by github.com/minio/mc/cmd.mainAdminSpeedTestSiteReplications
	github.com/minio/mc/cmd/support-perf-site-replication.go:85 +0x508
mc: MinIO performance report saved at sitea-perf_20230705175628.zip, please upload to SUBNET portal manually
```
@jiuker , there's a panic here

2023-07-06 02:57 UTC, poornas approved these changes

2023-07-06 05:30 UTC, harshavardhana requested changes

2023-07-06 05:30 UTC, harshavardhana commented on cmd/support-perf.go
> +	SiteReplicationResults *SiteReplicationTestResults `json:"site_replication,omitempty"`
```suggestion
	SiteReplicationResults *SiteReplicationTestResults `json:"siteReplication,omitempty"`
```

2023-07-06 06:45 UTC, harshavardhana approved these changes

2023-07-06 06:45 UTC, harshavardhana commented
Please fix the conflicts @jiuker by rebasing with master

2023-07-06 07:45 UTC, harshavardhana requested changes

2023-07-06 07:45 UTC, harshavardhana commented on cmd/support-perf-site-replication.go
> +func mainAdminSpeedTestSiteReplications(ctx *cli.Context, aliasedURL string, outCh chan<- PerfTestResult) error {
```suggestion
func mainAdminSpeedTestSiteReplication(ctx *cli.Context, aliasedURL string, outCh chan<- PerfTestResult) error {
```

2023-07-06 07:46 UTC, harshavardhana approved these changes

2023-07-06 07:47 UTC, harshavardhana requested changes

2023-07-06 07:47 UTC, harshavardhana commented on cmd/support-perf.go
> +			mainAdminSpeedTestSiteReplications(ctx, aliasedURL, resultCh)
```suggestion
			mainAdminSpeedTestSiteReplication(ctx, aliasedURL, resultCh)
```

2023-07-06 08:07 UTC, harshavardhana approved these changes

2023-07-06 08:07 UTC, merged