Enhance user info output with authentication info
minio/mc pull request #4613
Opened 2023-06-21 18:47 UTC by donatello

## Description

Return authentication metadata in user info command.

Needs https://github.com/minio/madmin-go/pull/201

## Motivation and Context

## How to test this PR?

Example outputs:

```
$ ./mc admin user info myminio foo
AccessKey: foo
Status: enabled
PolicyName: 
MemberOf: []
Authentication: builtin (foo)

$ ./mc admin user info myminio  uid=dillon,ou=people,ou=swengg,dc=min,dc=io
AccessKey: uid=dillon,ou=people,ou=swengg,dc=min,dc=io
Status: 
PolicyName: consoleAdmin
MemberOf: []
Authentication: ldap/localhost:1389 (uid=dillon,ou=people,ou=swengg,dc=min,dc=io)

```

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

2023-06-23 09:31 UTC, shtripat commented
@donatello for newly created users it does how the `Authentication` bit for existing ones it's empty. Is that expected behaviour?

```
$ ./mc admin user add myminio toobar toobar123                                                                                                     
Added user `toobar` successfully.

$ ./mc admin user info myminio toobar
AccessKey: toobar
Status: enabled
PolicyName: 
MemberOf: []
Authentication: builtin (toobar)

$ ./mc admin user list myminio
enabled    foobar1               non-root-user-policy

$ ./mc admin user info myminio foobar1
AccessKey: foobar1
Status: enabled
PolicyName: non-root-user-policy
MemberOf: [newgroup]
Authentication: 
```

2023-06-23 18:14 UTC, harshavardhana commented
yes it is since looks like the newer information is only captured for a newer set of users @shtripat - however we could deduce this on the server side ? @donatello for existing users that do not have this information?

Also if its not possible we should not show empty fields.

2023-06-24 00:03 UTC, donatello commented
Yes, I will send a fix

2023-06-30 17:33 UTC, donatello commented
Server PR is updated now, and this should work as expected @shtripat @harshavardhana

2023-07-01 14:41 UTC, harshavardhana requested changes

2023-07-01 14:41 UTC, harshavardhana commented on cmd/admin-user-add.go
> +				fmt.Sprintf("Authentication: %s", u.Authentication),
If u.Authentication is non-empty only we must print

2023-07-05 17:27 UTC, harshavardhana approved these changes

2023-07-06 05:07 UTC, shtripat approved these changes
LGTM. Verified

2023-07-07 05:25 UTC, merged