fix: allow cluster bucket export to export single bucket
minio/mc pull request #4614
Opened 2023-06-23 08:30 UTC by r-scheele

## Description
mc command to export single bucket information is not working. It worked a few days ago but now I am getting this error below..
`mc admin cluster bucket export play/abdul`
mc: <ERROR> Unable to download file data. createtemp azprod/rvm-prod-rvm-prod-metadata-: pattern contains path separator.
## How to test this PR?
`./mc admin cluster bucket export play/abdul`

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

2023-06-23 14:50 UTC, harshavardhana commented
> Please check this subnet issue here

@r-scheele we do reference private links in public issues. Ideally open a new GitHub issue if you must redacting private information or simply send a fix.

2023-06-23 14:59 UTC, r-scheele commented
Oh, apologies for that. I'll send a fix now

2023-06-23 17:39 UTC, harshavardhana requested changes

2023-06-23 17:39 UTC, harshavardhana commented on cmd/admin-cluster-bucket-export.go
> +	if err := os.MkdirAll(dir, 0o755); err != nil {
```suggestion
	if e := os.MkdirAll(dir, 0o755); e != nil {
```

2023-06-23 17:39 UTC, harshavardhana commented on cmd/admin-cluster-bucket-export.go
> +		log.Fatal(err)
```suggestion
		fatalIf(probe.NewError(e).Trace(dir))
```

2023-06-23 17:39 UTC, harshavardhana commented on cmd/cat-main.go
> +	checkCatSyntax(ctx)
```suggestion
	checkCatSyntax(ctx)
	
```

2023-06-23 18:11 UTC, harshavardhana approved these changes

2023-06-23 23:56 UTC, poornas approved these changes

2023-06-24 02:50 UTC, harshavardhana commented
Please resolve the conflicts @r-scheele - thanks

2023-06-24 08:38 UTC, merged