feat: support perf client to show `TX` from client to server
minio/mc pull request #4645
Opened 2023-07-25 02:17 UTC by jiuker

## Description

## Motivation and Context

 show `TX` from client to server

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

2023-08-09 16:20 UTC, harshavardhana requested changes

2023-08-10 02:16 UTC, jiuker commented on go.mod
> +replace github.com/minio/madmin-go/v3 => github.com/jiuker/madmin-go/v3 v3.0.0-20230807032717-2f88b58cc1fb
yes. I saw it. And I will make a change for 3.0.11. Hold on here

2023-08-10 12:06 UTC, shtripat commented on cmd/support-perf.go
> +	BytesSend uint64
%s/BytesSend/BytesSent/g

2023-08-10 12:06 UTC, shtripat commented on cmd/support-perf.go
> +	BytesSend uint64
Also add `json` mapping for `BytestSent` and `TimeSpent`

2023-08-10 12:38 UTC, shtripat approved these changes
lgtm

2023-08-10 14:16 UTC, harshavardhana approved these changes

2023-08-10 14:16 UTC, merged