Added `mc admin kms key list ALIAS` command
minio/mc pull request #4663
Opened 2023-08-17 13:12 UTC by shtripat

## Contribution License
All contributions in this pull request are licensed to the project maintainers 
under the terms of the [Apache 2 license] (https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
This change adds an option to list all KMS keys for a MinIO instance.

## Motivation and Context

## How to test this PR?
1. Deploy a MinIO instance with KES. Make sure KES is up and running

```
MINIO_KMS_KES_ENDPOINT=https://127.0.0.1:7373 MINIO_KMS_KES_CERT_FILE=minio.crt MINIO_KMS_KES_KEY_FILE=minio.key MINIO_KMS_KES_KEY_NAME=minio-default-key MINIO_KMS_KES_CAPATH=public.crt ./minio server ./test-kes
```

2. Create alias for the MinIO instanvce
3. Create few more KMS keys using command `mc admin kms  key create`
4. List all keys as below

```
$ ./mc admin kms key list myminio
Key: minio-default-key
Key: my-key-1
Key: my-key-2
Key: my-key-new
Key: my-key-new1

$ ./mc admin kms key list myminio --json 
{
    "key": "minio-default-key"
}
{
    "key": "my-key-1"
}
{
    "key": "my-key-2"
}
{
    "key": "my-key-new"
}
{
    "key": "my-key-new1"
}

```

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

2023-08-18 14:36 UTC, aead approved these changes

2023-08-18 15:42 UTC, harshavardhana requested changes

2023-08-18 15:42 UTC, harshavardhana commented on cmd/admin-kms-key-list.go
> +	return nil
We should actually print all the keys together @shtripat in a table form not one key per line.

We should also print when the key was created there is lot more information in kes.KeyInfo that can be pretty printed here.

It also looks like our `madmin-go` is behind what kes-go package can provide so we must update madin-go also to comply with the kes-go changes.

2023-08-18 15:56 UTC, shtripat commented on cmd/admin-kms-key-list.go
> +	return nil
Ok, will check and send PR for `madmin-go` and use the updated info here for displaying.

2023-08-21 08:21 UTC, aead commented on cmd/admin-kms-key-list.go
> +	return nil
I agree about the table format.

Unfortunately, listing keys does not return any CreatedAt data, key algorithm etc.
These fields are not set by current stateless KES servers since they would have to fetch each key from the backend KMS to send that information to the client - which is expensive.

Instead the API (stateful and stateless) KES servers expose will be: https://github.com/minio/kes/blob/854064f68ab89c895d2eea9d03f41829bfba08fd/internal/api/types.go#L99

So, listing - as of now - will only return the name of the item (key, policy, secret, ...)
In the future this might be expended but for now, only the key names are returned.

2023-08-21 08:32 UTC, harshavardhana commented on cmd/admin-kms-key-list.go
> +	return nil
That is fine then - let's put it into a table format for now.

2023-08-29 22:36 UTC, harshavardhana approved these changes

2023-08-29 22:36 UTC, merged