Accept --license flag in `mc license register`
minio/mc pull request #4795
Opened 2023-12-18 13:42 UTC by anjalshireesh

## Community Contribution License

All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license] (https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

If passed,

- validate and save it immediately in subnet config
- extract api key from it, and use for online registration with SUBNET (if `--airgap` is not passed)
- in case online registration with SUBNET fails for any reason, fallback to airgap mode (show URL to be visited on SUBNET)

## Motivation and Context

As SUBNET has moved to account level licenses, it is possible to download license event before the cluster is registered.
We'll now allow this license file to be used for registering clusters. This will simplify airgap mode registration as user will not
have to come back and update the license on mc/minio side.

## How to test this PR?

- Download license file from SUBNET
- Run `mc license register <alias> --license </path/to/minio.license>`
- Verify that registration is succesful

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

2023-12-18 19:29 UTC, harshavardhana requested changes

2023-12-18 19:29 UTC, harshavardhana commented on cmd/license-register.go
> +		Usage: "License of the account on SUBNET",
```suggestion
		Usage: "license of the account on SUBNET",
```

2023-12-19 05:03 UTC, anjalshireesh commented on cmd/license-register.go
> +		Usage: "License of the account on SUBNET",
done

2023-12-19 06:18 UTC, shtripat approved these changes
LGTM. Verified.

2023-12-19 12:23 UTC, klauspost approved these changes
LGTM

2023-12-20 08:44 UTC, harshavardhana approved these changes

2023-12-20 08:45 UTC, merged