feat: add put action
minio/mc pull request #4839
Opened 2024-02-01 09:31 UTC by jiuker

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

add put action support -s size -P part_numbers

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

2024-02-03 08:08 UTC, harshavardhana requested changes

2024-02-03 08:08 UTC, harshavardhana commented on cmd/client-s3.go
> +		}
we can't add random ENVs like this @jiuker. Please revert this change.

2024-02-03 08:08 UTC, harshavardhana commented on cmd/put-main.go
> +// Copyright (c) 2015-2022 MinIO, Inc.
```suggestion
// Copyright (c) 2015-2024 MinIO, Inc.
```

2024-02-03 08:08 UTC, harshavardhana commented on cmd/put-main.go
> +			Name:  "P",
```suggestion
			Name:  "parallel, P",
```

2024-02-03 08:08 UTC, harshavardhana commented on cmd/put-main.go
> +			Usage: "parts number",
```suggestion
			Usage: "upload number of parts in parallel",
```

2024-02-03 08:08 UTC, harshavardhana commented on cmd/put-main.go
> +			Name:  "s",
```suggestion
			Name:  "part-size, s",
```

2024-02-03 08:08 UTC, harshavardhana commented on cmd/put-main.go
> +	Usage:        "put local objects to s3",
```suggestion
	Usage:        "upload local objects to object storage",
```

2024-02-03 08:08 UTC, harshavardhana commented on cmd/put-main.go
> +	}
```suggestion
```

2024-02-03 08:08 UTC, harshavardhana commented on cmd/put-main.go
> +	fmt.Println(errSeen)
?

2024-02-03 08:08 UTC, harshavardhana commented on cmd/put-main.go
> +	//return mainCopy(cliCtx)
?

2024-02-03 08:08 UTC, harshavardhana commented on cmd/put-main.go
> +	quite := make(chan struct{})
```suggestion
	quit := make(chan struct{})
```
?

2024-02-04 06:58 UTC, jiuker commented
```log
MacBook-Pro mc % mc admin trace -a minio | grep s3.
2024-02-04T14:57:57.554 [200 OK] s3.NewMultipartUpload 127.0.0.1:9000/mytest/minio-server?uploads=  127.0.0.1         2.48ms       ↑ 106 B ↓ 315 B
2024-02-04T14:57:57.557 [200 OK] s3.PutObjectPart 127.0.0.1:9000/mytest/minio-server?partNumber=2&uploadId=Mzk1MTYyZDAtNDkzYi00MTMyLTk5ZDctYTRlMTYyNzIzZTM3LjI2MDdlMWRhLTRhMmYtNDk3YS1iMDlmLWJkNjM1ZDcxYWY1Yg  127.0.0.1         268.191ms    ↑ 31 MiB ↓ 0 B
2024-02-04T14:57:57.558 [200 OK] s3.PutObjectPart 127.0.0.1:9000/mytest/minio-server?partNumber=1&uploadId=Mzk1MTYyZDAtNDkzYi00MTMyLTk5ZDctYTRlMTYyNzIzZTM3LjI2MDdlMWRhLTRhMmYtNDk3YS1iMDlmLWJkNjM1ZDcxYWY1Yg  127.0.0.1         270.64ms     ↑ 31 MiB ↓ 0 B
2024-02-04T14:57:57.830 [200 OK] s3.PutObjectPart 127.0.0.1:9000/mytest/minio-server?partNumber=4&uploadId=Mzk1MTYyZDAtNDkzYi00MTMyLTk5ZDctYTRlMTYyNzIzZTM3LjI2MDdlMWRhLTRhMmYtNDk3YS1iMDlmLWJkNjM1ZDcxYWY1Yg  127.0.0.1         317.571ms    ↑ 31 MiB ↓ 0 B
2024-02-04T14:57:57.826 [200 OK] s3.PutObjectPart 127.0.0.1:9000/mytest/minio-server?partNumber=3&uploadId=Mzk1MTYyZDAtNDkzYi00MTMyLTk5ZDctYTRlMTYyNzIzZTM3LjI2MDdlMWRhLTRhMmYtNDk3YS1iMDlmLWJkNjM1ZDcxYWY1Yg  127.0.0.1         324.7ms      ↑ 31 MiB ↓ 0 B
2024-02-04T14:57:58.149 [200 OK] s3.PutObjectPart 127.0.0.1:9000/mytest/minio-server?partNumber=5&uploadId=Mzk1MTYyZDAtNDkzYi00MTMyLTk5ZDctYTRlMTYyNzIzZTM3LjI2MDdlMWRhLTRhMmYtNDk3YS1iMDlmLWJkNjM1ZDcxYWY1Yg  127.0.0.1         31.538ms     ↑ 3.2 MiB ↓ 0 B
2024-02-04T14:57:58.181 [200 OK] s3.CompleteMultipartUpload 127.0.0.1:9000/mytest/minio-server?uploadId=Mzk1MTYyZDAtNDkzYi00MTMyLTk5ZDctYTRlMTYyNzIzZTM3LjI2MDdlMWRhLTRhMmYtNDk3YS1iMDlmLWJkNjM1ZDcxYWY1Yg  127.0.0.1         8.829ms      ↑ 625 B ↓ 315 B

```
@harshavardhana

2024-02-05 12:14 UTC, vadmeste reviewed
I am not sure about the exact requirements here, can you explain more @jiuker ? because we already have 'mc cp'. I am not sure why we are adding 'mc put' command here.

2024-02-05 17:40 UTC, zveinn commented
Did you run functional-test.sh on this ? 

This PR makes changes to code used by many commands, so we need to be very careful here. I will review this tomorrow.

2024-02-05 20:39 UTC, harshavardhana commented
mc cp is costly, mc put is what it is meant for just doing PUTs does not have the burden of cp and it won't make any extra calls other than PUT or multipart upload

2024-02-06 04:58 UTC, shtripat commented on cmd/put-main.go
> +  MC_ENCRYPT:      list of comma delimited prefixes
Cant we have flags like `--encrypt` and `--encrypt-key` like `mc cp` command? ENV is fine but additionally we can have command line flags as well.

2024-02-06 04:58 UTC, shtripat commented on cmd/put-main.go
> +// mainPut is the entry point for cp command.
```suggestion
// mainPut is the entry point for put command.
```

2024-02-06 04:58 UTC, shtripat commented on cmd/put-main.go
> +		fatalIf(probe.NewError(perr), "Unable to parse size")
```suggestion
		fatalIf(probe.NewError(perr), "Unable to parse part size")
```

2024-02-06 09:27 UTC, zveinn commented on cmd/put-main.go
> +  MC_ENCRYPT:      list of comma delimited prefixes
We are replacing the encrypt flags with new ones soon, I will add this after that happens.

2024-02-06 15:44 UTC, shtripat reviewed
Few minor ones. command works as expected though.

2024-02-06 15:44 UTC, shtripat commented on cmd/put-main.go
> +	putFlags = []cli.Flag{
any reason to keep one short flag uppercase and one lowercase :)

2024-02-06 15:44 UTC, shtripat commented on cmd/put-main.go
> +			ignoreBucketExists: true,
somehow I feel `checkBucketExists` as better name or else `ignoreBucketExistsCheck`

2024-02-07 10:42 UTC, shtripat commented on cmd/put-main.go
> +	Usage:        "upload local objects to object storage",
```suggestion
	Usage:        "upload local object to s3 object storage",
```
Removed plural for `object` as at a time we can upload/put one object

2024-02-07 10:42 UTC, shtripat commented on cmd/put-main.go
> +  01. Put a list of objects from local file system to Amazon S3 cloud storage.
I dont think we can put a list of objects in one shot so we should rephrase the text here. Better help examples could be
```
1. Put an object from local file system to S3 storage
{{.Prompt}} {{.HelpName}} path-to/object ALIAS/BUCKET
2. Put an object from local file system to S3 bucket with name
{{.Prompt}} {{.HelpName}} path-to/object ALIAS/BUCKET/OBJECT-NAME
3. Put an object from local file system to S3 bucket under a prefix
{{.Prompt}} {{.HelpName}} path-to/object ALIAS/BUCKET/PREFIX/
```
just suggestion if looks good.

2024-02-08 07:33 UTC, shtripat approved these changes
lgtm

2024-02-11 06:40 UTC, harshavardhana requested changes

2024-02-11 06:40 UTC, harshavardhana commented on cmd/put-main.go
> +		},
```suggestion
		cli.IntFlag{
			Name:  "parallel, P",
			Usage: "upload number of parts in parallel",
			Value: 4,
		},
```

Must have a default value set to '4'

2024-02-11 06:40 UTC, harshavardhana commented on cmd/put-main.go
> +		},
```suggestion
		cli.StringFlag{
			Name:  "part-size, s",
			Usage: "each part size",
			Value: "16MiB",
		},
```

Must have a default value.

2024-02-11 06:40 UTC, harshavardhana commented on cmd/put-main.go
> +	if threads == 0 {
validate for threads < 0

2024-02-11 06:40 UTC, harshavardhana commented on cmd/put-main.go
> +	os.Setenv("MC_UPLOAD_MULTIPART_SIZE", size)
```suggestion
	os.Setenv("MC_UPLOAD_MULTIPART_SIZE", size)
```

This is not an expected pattern of passing values; please feel free to make relevant changes to the function doCopy() to pass the information pertinent to the s3Client.

You do not have to re-use the ENVs in this manner; this is not the correct style that we follow in the MC codebase.

2024-02-20 06:36 UTC, harshavardhana approved these changes

2024-02-20 06:36 UTC, merged