Enable --expired-object-all-versions
minio/mc pull request #4840
Opened 2024-02-02 18:40 UTC by shtripat

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

## Motivation and Context

## How to test this PR?
mc ilm rule add --expired-object-all-versions ALIAS/BUCKET

needs: https://github.com/minio/minio-go/pull/1927

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

2024-02-14 21:19 UTC, harshavardhana requested changes

2024-02-14 21:19 UTC, harshavardhana commented on go.mod
> +replace github.com/minio/minio-go/v7 v7.0.66 => github.com/shtripat/minio-go/v7 v7.0.0-20240202175226-e4e2f9e24339
please update the replace flag

2024-02-15 04:26 UTC, shtripat commented on go.mod
> +replace github.com/minio/minio-go/v7 v7.0.66 => github.com/shtripat/minio-go/v7 v7.0.0-20240202175226-e4e2f9e24339
done

2024-02-19 13:28 UTC, vadmeste requested changes
Few questions

2024-02-19 13:28 UTC, vadmeste commented on cmd/ilm-rule-add.go
> +		Name:  "expired-object-all-versions",
maybe 'expire-all-object-versions' ?

2024-02-19 13:28 UTC, vadmeste commented on cmd/ilm/options.go
> +		if opts.ExpiredObjectAllversions != nil {
why this 'if' is inside 	'} else if opts.ExpiredObjectDeleteMarker != nil {' ?

2024-02-19 13:28 UTC, vadmeste commented on cmd/ilm/options.go
> +			dest.Expiration.Date = lifecycle.ExpirationDate{}
Why you have to reset both fields here ? this is different to expired object delete marker

2024-02-19 15:42 UTC, harshavardhana approved these changes

2024-02-20 10:37 UTC, vadmeste approved these changes
LGTM

2024-02-20 13:12 UTC, prakashsvmx approved these changes
Tested . LGTM :+1:

2024-02-20 14:47 UTC, harshavardhana approved these changes

2024-02-20 14:47 UTC, merged