removing deprecated encryption keys ( new keys will be added soon )
minio/mc pull request #4853
Opened 2024-02-21 18:36 UTC by zveinn

AB wants us to remove the old encryption keys from the mc. This will happen in a PR I will make next week. Because of the deprecation happening we should not include the old keys in these new commands. I will add the new keys to put and get in the coming PR.

2024-02-22 02:21 UTC, jiuker approved these changes

2024-02-27 22:51 UTC, bh4t commented
@harshavardhana @kannappanr can you please review this?

2024-02-29 08:21 UTC, jiuker requested changes
`get-main.go` have that too.

2024-02-29 15:43 UTC, zveinn commented
It´s fine.. I´ll just close this PR and adjust it in the upcoming PR. A few days probably won´t matter.

2024-02-29 15:43 UTC, closed without merging