fix: fix_pg_bar
minio/mc pull request #4857
Opened 2024-02-23 03:51 UTC by jiuker

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

```
MacBook-Pro mc % ./mc put -s 32mb -P 2 /Users/guozhili/workspace/go/src/minio/minio-server minio/mytest
...i/workspace/go/src/minio/minio-server: 127.30 MiB / 127.30 MiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.70 MiB/s 0s
MacBook-Pro mc % ./mc put -s 32mb -P 2 /Users/workspace/go/src/minio/minio-server minio/mytest1
mc: <ERROR> Bucket `mytest1` does not exist.
MacBook-Pro mc % ./mc put -s 32mb -P 2 /Users/workspace/go/src/minio/minio-server1 minio/mytest 
mc: <ERROR> Unable to upload. Requested path `/Users/workspace/go/src/minio/minio-server1` not found
MacBook-Pro mc % ./mc put -s 32mb -P 2 /Users/workspace/go/src/minio/minio-server /minio/mytest
mc: <ERROR> Unable to upload. Target is not s3.
MacBook-Pro mc % ./mc put -s 32mb -P 2 minio/minio-server minio/mytest 
mc: <ERROR> Unable to upload. Bucket `minio-server` does not exist.
MacBook-Pro mc % ./mc put -s 32mb -P 2 minio/mytest/minio-server minio/mytest
mc: <ERROR> Unable to upload. Source is not local filepath.
MacBook-Pro mc % 

```

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

2024-02-23 09:37 UTC, shtripat approved these changes
lgtm

2024-02-23 16:33 UTC, harshavardhana requested changes
White bar is not visible on white terminals which are default. 

We should chose color palette for the right terminal colors, white is actually worst of all.

We can never use white or black

2024-02-24 00:48 UTC, harshavardhana commented on cmd/progress-bar.go
> +	console.SetColor("Bar", color.New(color.FgWhite, color.Bold))
```suggestion
	console.SetColor("Bar", color.New(color.FgYellow, color.Bold))
```

2024-02-24 00:51 UTC, harshavardhana commented on cmd/put-main.go
> +func showLastProgressBar(pg ProgressReader, err error) {
```suggestion
func showLastProgressBar(pg ProgressReader, e error) {
```

2024-02-24 00:51 UTC, harshavardhana commented on cmd/put-main.go
> +	if err != nil {
```suggestion
	if e != nil {
```

2024-02-24 00:51 UTC, harshavardhana commented on cmd/put-main.go
> +func mainPut(cliCtx *cli.Context) (rerr error) {
```suggestion
func mainPut(cliCtx *cli.Context) (e error) {
```

2024-02-24 00:51 UTC, harshavardhana commented on cmd/get-main.go
> +func mainGet(cliCtx *cli.Context) (rerr error) {
```suggestion
func mainGet(cliCtx *cli.Context) (e error) {
```

2024-02-24 00:52 UTC, harshavardhana commented on cmd/get-main.go
> +				showLastProgressBar(pg, rerr)
```suggestion
				showLastProgressBar(pg, e)
```

2024-02-24 00:52 UTC, harshavardhana commented on cmd/get-main.go
> +				rerr = urls.Error.ToGoError()
```suggestion
				e = urls.Error.ToGoError()
```

2024-02-24 01:33 UTC, harshavardhana approved these changes

2024-02-24 01:33 UTC, merged