Functional tests: add a parameter for the full site cleaning test
minio/mc pull request #4877
Opened 2024-03-16 15:19 UTC by davlgd

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

Fix #4876 

The latest `mc rb` test clean all the site data, and on the demo site, there are sometimes WORM objects put by some users and it leads to an failure. This test should only be run on sites on which the user knows he can clean everything without errors

## Motivation and Context

I need to run functional tests without errors on the demo site, even if some user put WORM objects in it. The `COMPLETE_RB_TEST` allow to run the "clean everything" test when the user needs it. The parameter name can be changed if it doesn't comply to any mc development rule.

## How to test this PR?

Launch `make test` with `COMPLETE_RB_TEST` parameter set to false/true

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

2024-03-19 14:26 UTC, shtripat commented on functional-tests.sh
> +    if [ "${COMPLETE_RB_TEST}" = "true" ]; then
Shouldn't this be `if [ "${COMPLETE_RB_TEST}" == "true" ]; then` ?

2024-03-20 21:08 UTC, harshavardhana requested changes

2024-03-20 21:08 UTC, harshavardhana commented on functional-tests.sh
> +COMPLETE_RB_TEST=false
```suggestion
COMPLETE_RB_TEST=true
```

2024-03-21 04:58 UTC, shtripat approved these changes

2024-03-26 18:42 UTC, bh4t commented
@harshavardhana PTAL when you get a chance.

2024-03-26 18:58 UTC, harshavardhana approved these changes

2024-03-30 15:29 UTC, merged