Use new batch status api `/status-job`
minio/mc pull request #4930
Opened 2024-05-09 12:24 UTC by shtripat

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

## Motivation and Context

## How to test this PR?
run a batch replication and then `mc batch status ALIAS JOB-ID`

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

2024-05-09 12:24 UTC, shtripat commented
Needs: https://github.com/minio/minio/pull/19679

2024-07-02 09:28 UTC, harshavardhana approved these changes

2024-07-02 09:43 UTC, vadmeste requested changes
@shtripat I think we should keep client.Metrics() batch because it is much less expensive than client.BatchJobStatus, also client.Metrics() provides realtime information and it is better to keep it.

However client.BatchJobStatus() is useful when the job finishes, where client.Metrics() can be cleared (because it is in-memory server side data).

So overall, I think it is enough to add client.BatchJobStatus() only when the job is finished (nosuchJob in line 66:84)

2024-07-02 10:08 UTC, shtripat commented
> @shtripat I think we should keep client.Metrics() batch because it is much less expensive than client.BatchJobStatus, also client.Metrics() provides realtime information and it is better to keep it.
> 
> However client.BatchJobStatus() is useful when the job finishes, where client.Metrics() can be cleared (because it is in-memory server side data).
> 
> So overall, I think it is enough to add client.BatchJobStatus() only when the job is finished (nosuchJob in line 66:84)

@vadmeste do you mean a change as below
```
diff --git a/cmd/batch-status.go b/cmd/batch-status.go
index 67d2d7de..10b8dbac 100644
--- a/cmd/batch-status.go
+++ b/cmd/batch-status.go
@@ -2,6 +2,7 @@ package cmd
 
 import (
        "context"
+       "errors"
        "fmt"
        "strings"
        "time"
@@ -79,6 +80,8 @@ func mainBatchStatus(ctx *cli.Context) error {
        ctxt, cancel := context.WithCancel(globalContext)
        defer cancel()
 
+       ui := tea.NewProgram(initBatchJobMetricsUI(jobID))
+
        _, e := client.DescribeBatchJob(ctxt, jobID)
        nosuchJob := madmin.ToErrorResponse(e).Code == "XMinioAdminNoSuchJob"
        if nosuchJob {
@@ -86,26 +89,57 @@ func mainBatchStatus(ctx *cli.Context) error {
                if !globalJSON {
                        console.Infoln("Unable to find an active job, attempting to list from previously run jobs")
                }
-       }
-       fatalIf(probe.NewError(e), "Unable to lookup job status")
-
-       ui := tea.NewProgram(initBatchJobMetricsUI(jobID))
-       go func() {
-               res, e := client.BatchJobStatus(ctxt, jobID)
-               fatalIf(probe.NewError(e), "Unable to lookup job status")
-               if globalJSON {
-                       printMsg(batchJobStatusMessage{
-                               Status: "success",
-                               Metric: res.LastMetric,
+               go func() {
+                       res, e := client.BatchJobStatus(ctxt, jobID)
+                       fatalIf(probe.NewError(e), "Unable to lookup job status")
+                       if globalJSON {
+                               printMsg(batchJobStatusMessage{
+                                       Status: "success",
+                                       Metric: res.LastMetric,
+                               })
+                               if res.LastMetric.Complete || res.LastMetric.Failed {
+                                       cancel()
+                                       return
+                               }
+                       } else {
+                               ui.Send(res.LastMetric)
+                       }
+               }()
+       } else {
+               go func() {
+                       opts := madmin.MetricsOptions{
+                               Type:     madmin.MetricsBatchJobs,
+                               ByJobID:  jobID,
+                               Interval: time.Second,
+                       }
+                       e := client.Metrics(ctxt, opts, func(metrics madmin.RealtimeMetrics) {
+                               if globalJSON {
+                                       if metrics.Aggregated.BatchJobs == nil {
+                                               cancel()
+                                               return
+                                       }
+
+                                       job, ok := metrics.Aggregated.BatchJobs.Jobs[jobID]
+                                       if !ok {
+                                               cancel()
+                                               return
+                                       }
+
+                                       printMsg(metricsMessage{RealtimeMetrics: metrics})
+                                       if job.Complete || job.Failed {
+                                               cancel()
+                                               return
+                                       }
+                               } else {
+                                       ui.Send(metrics)
+                               }
                        })
-                       if res.LastMetric.Complete || res.LastMetric.Failed {
-                               cancel()
-                               return
+                       if e != nil && !errors.Is(e, context.Canceled) {
+                               fatalIf(probe.NewError(e).Trace(ctx.Args()...), "Unable to get current batch status")
                        }
-               } else {
-                       ui.Send(res.LastMetric)
-               }
-       }()
+               }()
+       }
+       fatalIf(probe.NewError(e), "Unable to lookup job status")
 
        if !globalJSON {
                if _, e := ui.Run(); e != nil {
```

2024-07-02 12:11 UTC, shtripat commented
Its not working as expected and would need more work.

2024-07-02 15:14 UTC, harshavardhana approved these changes

2024-07-02 15:28 UTC, vadmeste approved these changes
LGTM

2024-07-02 15:29 UTC, merged