Rework `mc idp ldap accesskey list` to use new API endpoint
minio/mc pull request #4946
Opened 2024-05-29 22:18 UTC by taran-p

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
INCOMPLETE

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

2024-06-25 20:34 UTC, harshavardhana requested changes
can you show how the terminal UI looks like?

2024-06-25 21:16 UTC, taran-p commented
![image](https://github.com/minio/mc/assets/84724408/7cc28f8a-954a-4a54-b8ef-5f8284ac0ba3)
@harshavardhana

2024-07-17 23:16 UTC, donatello approved these changes

2024-07-31 15:57 UTC, harshavardhana commented
> ![image](https://private-user-images.githubusercontent.com/84724408/342933900-7cc28f8a-954a-4a54-b8ef-5f8284ac0ba3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDE2ODIsIm5iZiI6MTcyMjQ0MTM4MiwicGF0aCI6Ii84NDcyNDQwOC8zNDI5MzM5MDAtN2NjMjhmOGEtOTU0YS00YTU0LWI4ZWYtNWY4Mjg0YWMwYmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE1NTYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNzZjOWE1OGM0OTJlMThiMWE1MTNhMzllNmE5NWU4Mjk2MTRlZTBiNGVjZWRjNDdiYmVhODhkNzY2OWZjZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pb2I3pe-2N7-NxlTydnXxaZGZKp3Y7Z2rbxOv8mjKj4) @harshavardhana

This UI looks a bit mouthful; changing this and simplifying it.

2024-07-31 15:58 UTC, merged