iam export:designate zip file name
minio/mc pull request #4995
Opened 2024-07-24 07:19 UTC by dormanze

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

## Motivation and Context

## How to test this PR?

![image](https://github.com/user-attachments/assets/7ec451f6-f6d0-43f4-93c0-274df1c4766a)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

2024-07-24 14:27 UTC, klauspost commented
It seems a bit contrary to the usual design that the parameter is always assumed to be local path and not an alias.

Adding a `-o=/tmp/myminio-iam.zip` that allows to override the output path seems more appropriate to me.

2024-07-27 17:03 UTC, harshavardhana requested changes

2024-07-27 17:03 UTC, harshavardhana commented on cmd/admin-cluster-iam-export.go
> +			Name:  "overwrite,o",
```suggestion
			Name:  "output,o",
```

2024-07-27 17:03 UTC, harshavardhana commented on cmd/admin-cluster-iam-export.go
> +			Usage: "overwrite iam export file path",
```suggestion
			Usage: "output iam export to a custom file path",
```

2024-07-27 17:03 UTC, harshavardhana commented on cmd/admin-cluster-iam-export.go
> +  2. Download all IAM metadata for cluster into designated zip file.
```suggestion
  2. Download all IAM metadata to a custom file.
```

2024-08-05 11:38 UTC, klauspost commented on cmd/admin-cluster-iam-export.go
> +	if len(ctx.Args()) != 1 && len(ctx.Args()) != 2 {
Leftover?

2024-08-05 12:17 UTC, klauspost approved these changes

2024-08-09 07:50 UTC, zveinn commented on cmd/admin-cluster-iam-export.go
> +  2. Download all IAM metadata to a custom file.
Please add some spacing in the help menu .. a single space should do

2024-08-09 07:54 UTC, zveinn approved these changes

2024-08-12 12:54 UTC, zveinn approved these changes

2024-09-09 16:36 UTC, klauspost commented
@dormanze I presume it is a script, but could you please turn off the automatic merge with master? It is very noisy and we need to manually re-run tests every time.

2024-09-16 17:31 UTC, donatello approved these changes

2024-09-16 17:43 UTC, merged