Import bucket metadata must show CORS and general errors if any are found
minio/mc pull request #5001
Opened 2024-07-29 05:45 UTC by marktheunissen

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

- Fix a bug where any error on the zip file itself was not reported, e.g. malformed directory.
- Report whether CORS bucket settings were imported successfully

## Motivation and Context

## How to test this PR?

Example of failed import errors, with this PR:

```
0/2 buckets were imported successfully.
Errors:

Name      : BADFORMAT/corsexporttest/cors.xml
  Error:  malformed zip - expecting format bucket/<config.json>

Name      : corsexporttest
  Notification:  ✔
  Quota:  ✔
  CORS:  ✗
```

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fmc%2fpull%2fNNNNN)

2024-07-31 06:11 UTC, marktheunissen commented on go.mod
> +replace github.com/minio/pkg/v3 => github.com/marktheunissen/pkg/v3 v3.0.0-20240726014105-5a91ee390421
Remove when dependency is merged

2024-07-31 21:46 UTC, poornas approved these changes

2024-08-05 14:19 UTC, klauspost approved these changes
LGTM 👍🏼

2024-08-05 15:31 UTC, harshavardhana requested changes

2024-08-05 15:31 UTC, harshavardhana commented on go.sum
> +github.com/marktheunissen/madmin-go/v3 v3.0.0-20240730061730-2d8255671cb3 h1:3m57M9Lq3JauBsFqgpkPEIeDW4+EogeKr3bMT1zJfkM=
Please update these.

2024-08-06 00:40 UTC, marktheunissen commented on go.sum
> +github.com/marktheunissen/madmin-go/v3 v3.0.0-20240730061730-2d8255671cb3 h1:3m57M9Lq3JauBsFqgpkPEIeDW4+EogeKr3bMT1zJfkM=
done

2024-08-12 05:03 UTC, marktheunissen commented
@harshavardhana please re-review and merge if happy, thanks.

2024-08-12 11:08 UTC, zveinn approved these changes
LGTM

2024-08-13 03:08 UTC, merged